import {VERSION,DEFAULT_SETTINGS} from './config.js';
import {initialize,loadState,saveState,requestPersistence} from './db.js';
import {character,avatarURL,CHARACTERS,preloadCharacter} from './characters.js';
import {Game} from './game.js';
import {updateStats,weak,makeChoices,buildQueue} from './learning.js';
import {masteryCounts} from './stats.js';
import {renderEditor} from './editor.js';
import {exportBackup,exportAI,validateImport,applyImport,exampleAI,validateSettings} from './backup.js';
import {AudioEngine} from './audio.js';
import {Effects} from './effects.js';
import {escapeHTML as h,toast,downloadJSON,showDialog,closeDialog,bindDialogClose,dateLabel,now} from './utils.js';
const main=document.querySelector('#main'),nav=document.querySelector('#nav'),audio=new AudioEngine(),effects=new Effects();
let state,selectedDeck,page='home',game,installPrompt,commitQueue=Promise.resolve(),busy=false;
const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('yuu-recall-burst-changes'):null;
const lock=fn=>navigator.locks?navigator.locks.request('yuu-recall-burst-write',fn):fn();
async function commit(mutator,rerender=true){const task=commitQueue.catch(()=>{}).then(()=>lock(async()=>{const latest=await loadState();const next=structuredClone(latest);mutator(next);await saveState(next);state=next;channel?.postMessage('changed');if(rerender&&!game)render();}));commitQueue=task;return task;}
channel&&(channel.onmessage=async()=>{state=await loadState();if(!game&&!document.querySelector('#dialog').open)render();});
function count(deckId){return state.questions.filter(q=>q.deckId===deckId&&q.enabled).length;}
function currentDeck(){return state.decks.find(d=>d.id===selectedDeck)??state.decks[0];}
function totalWeak(deckId){return state.questions.filter(q=>q.enabled&&(!deckId||q.deckId===deckId)&&weak(state.questionStats.find(s=>s.id===`${q.id}:${state.settings.direction}`))).length;}
function render(){if(!state)return;page=(location.hash.slice(1)||'home');if(!['home','editor','history','settings'].includes(page))page='home';nav.hidden=false;nav.querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.className='';document.body.classList.remove('playing');if(page==='home')renderHome();if(page==='editor')renderEditor({main,state,selectedDeck,onCommit:commit,onSelect:id=>{selectedDeck=id;render();}});if(page==='history')renderHistory();if(page==='settings')renderSettings();}
function renderHome(){const c=character(state.settings.characterId);const deck=currentDeck();selectedDeck=deck?.id;const mastery=masteryCounts(state.questions,state.questionStats,state.settings.direction);const last=state.sessions.filter(s=>!s.aborted).at(-1);const best=Math.max(0,...state.sessions.map(s=>s.maxCombo));main.innerHTML=`<section class="home"><div class="home-hero"><div class="hero-copy"><span class="eyebrow">RECALL. REACT. REPEAT.</span><h1>思い出すたび、<br><em>記憶がバースト。</em></h1><p>${h(c.name)}といっしょに、もう1問。</p><div class="hero-chip"><i>●</i> 10 COMBO → RECALL FEVER</div></div><div class="home-avatar"><div class="hero-orbit"></div><img src="${avatarURL(state.settings.characterId,'neutral')}" alt="ナビゲーター ${h(c.name)}"><span class="avatar-name">${h(c.id.toUpperCase())}</span></div></div><div class="intro-line"><span>今日は何を覚える？</span><span class="mini-label">${state.settings.mode==='choice'?'4択':'RECALL'} · ${state.settings.difficulty}</span></div><div class="deck-grid">${state.decks.map((d,i)=>{const n=count(d.id);return `<button class="deck-card ${d.id===deck?.id?'selected':''}" data-deck="${h(d.id)}"><div class="deck-symbol">${['◈','✧','◇','ϟ'][i%4]}</div><div><strong>${h(d.name)}</strong><small>${n}問 · 苦手${totalWeak(d.id)}問</small></div><span class="deck-check">${d.id===deck?.id?'●':'○'}</span></button>`;}).join('')||'<div class="empty"><p>最初のジャンルを作ろう。</p><a href="#editor" class="secondary">問題を追加</a></div>'}</div><div class="play-actions"><button id="start" class="start-button" ${deck&&count(deck.id)?'':'disabled'}><span>START BURST</span><small>${state.settings.questionCount}問にチャレンジ <b>→</b></small></button><button id="weak-play" class="review-button" ${deck&&totalWeak(deck.id)?'':'disabled'}><span>↻</span><div>苦手だけプレイ<small>選択ジャンルの苦手を優先</small></div></button></div><div class="home-stats"><div><strong>${state.sessions.length}</strong><small>SESSIONS</small></div><div><strong>${best}</strong><small>BEST COMBO</small></div><div><strong>${mastery.MASTERED}</strong><small>MASTERED</small></div></div>${last?`<div class="recent"><small>RECENT PLAY</small><p>${h(last.deckName)} <span>${last.accuracy}% · ${dateLabel(last.finishedAt)}</span></p></div>`:''}<p class="home-tip">正解で${h(c.name)}がリアクション。<br>10連続正解で光も音もFEVERへ。</p></section>`;main.querySelectorAll('[data-deck]').forEach(e=>e.onclick=()=>{selectedDeck=e.dataset.deck;renderHome();});main.querySelector('#start').onclick=()=>start(false);main.querySelector('#weak-play').onclick=()=>start(true);}
async function start(onlyWeak){if(busy||game)return;const deck=currentDeck();if(!deck)return;const pool=state.questions.filter(q=>q.deckId===deck.id&&q.enabled);const queue=buildQueue(pool,state.questionStats,state.settings.questionCount,state.settings.direction,onlyWeak);if(!queue.length){toast('対象の問題がないよ');return;}const inadequate=state.settings.mode==='choice'?queue.filter(q=>!makeChoices(q,pool,state.settings.direction)):[];if(inadequate.length){showDialog(`<h2>4択の候補を追加しよう</h2><p>「${h(inadequate[0].prompt)}」に、正解以外の候補が3つ必要だよ。</p><p>同じジャンルに異なる答えの問題を増やすか、問題編集で誤答候補を入れてね。逆方向では異なる問題文が4つ必要だよ。</p><div class="dialog-actions"><button id="use-recall" class="primary">Recallモードで遊ぶ</button><button data-close class="secondary">閉じる</button></div>`);bindDialogClose();document.querySelector('#use-recall').onclick=async()=>{await commit(s=>{s.settings.mode='recall';},false);closeDialog();start(onlyWeak);};return;}
 busy=true;main.querySelector('#start')?.setAttribute('disabled','');try{await audio.unlock(state.settings);await preloadCharacter(state.settings.characterId);await requestPersistence();await commit(s=>{const existing=s.appMeta.find(x=>x.id==='lastDeck');if(existing)existing.deckId=deck.id;else s.appMeta.push({id:'lastDeck',deckId:deck.id});},false);document.body.classList.add('playing');nav.hidden=true;game=new Game({main,questions:pool,stats:state.questionStats,settings:structuredClone(state.settings),deck,onlyWeak,audio,effects,onAnswer:r=>commit(s=>{const key=`${r.questionId}:${r.direction}`;const updated=updateStats(s.questionStats.find(x=>x.id===key),r.questionId,r.grade!=='MISS',r.ms,r.direction);s.questionStats=s.questionStats.filter(x=>x.id!==key);s.questionStats.push(updated);},false),onFinish:async result=>{game=null;try{await commit(s=>s.sessions.push(result),false);renderResult(result);}catch(e){main.innerHTML='<section class="page"><h1>結果を保存できませんでした</h1><p>空き容量を確認して再試行してください。</p><button id="retry-result" class="primary">保存を再試行</button></section>';main.querySelector('#retry-result').onclick=async()=>{await commit(s=>{if(!s.sessions.some(x=>x.id===result.id))s.sessions.push(result);},false);renderResult(result);};throw e;}}});game.start();}finally{busy=false;}}
function renderResult(result){document.body.classList.remove('playing');nav.hidden=false;main.innerHTML=`<section class="results"><span class="eyebrow">${result.aborted?'SESSION SAVED':result.perfectClear?'ALL MEMORIES CONNECTED':'NICE RECALL'}</span><h1>${result.aborted?'途中の記録':result.perfectClear?'PERFECT CLEAR':'CLEAR!'}</h1><div class="result-score"><small>TOTAL SCORE</small><strong>${result.score.toLocaleString()}</strong><span>${h(result.deckName)}</span></div><div class="result-grid"><div><strong>${result.accuracy}%</strong><small>正答率</small></div><div><strong>${result.maxCombo}</strong><small>最大COMBO</small></div><div><strong>${Math.round(result.durationMs/1000)}秒</strong><small>プレイ時間</small></div></div><div class="grade-grid">${['PERFECT','GREAT','GOOD','MISS'].map(g=>`<div data-grade="${g}"><small>${g}</small><strong>${result[g]}</strong></div>`).join('')}</div><div class="card"><h2>今回覚えきれていない問題</h2>${[...new Map(result.records.filter(r=>r.grade==='MISS').map(r=>[r.questionId,r])).values()].map(r=>`<p class="miss-row"><strong>${h(r.prompt)}</strong><span>→ ${h(r.answer)}</span></p>`).join('')||'<p>全問正解！ この調子で覚えていこう ✨</p>'}</div><div class="result-actions"><button id="again" class="primary">もう1回 BURST</button><button id="result-weak" class="secondary" ${totalWeak(result.deckId)?'':'disabled'}>苦手を復習</button><button id="home" class="quiet">ホームへ</button></div></section>`;selectedDeck=result.deckId;main.querySelector('#again').onclick=()=>start(false);main.querySelector('#result-weak').onclick=()=>start(true);main.querySelector('#home').onclick=()=>{location.hash='home';render();};window.scrollTo(0,0);}
function renderHistory(){const mastery=masteryCounts(state.questions,state.questionStats,state.settings.direction);main.innerHTML=`<section class="page"><span class="eyebrow">EVERY RECALL COUNTS</span><h1>記憶のあしあと</h1><div class="mastery-grid">${Object.entries(mastery).map(([label,value])=>`<div class="card"><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><p class="hint-text">${state.settings.direction==='reverse'?'逆方向':'通常方向'}の習熟度。正答率・連続正解・回答速度で更新するよ。</p><div class="session-list">${[...state.sessions].reverse().map(s=>`<button class="session card" data-session="${h(s.id)}"><div><strong>${h(s.deckName)}</strong><small>${dateLabel(s.finishedAt)} · ${s.mode==='recall'?'Recall':'4択'}${s.aborted?' · 途中終了':''}</small></div><div><strong>${s.score.toLocaleString()}</strong><small>${s.accuracy}% · ${s.maxCombo} COMBO</small></div></button>`).join('')||'<div class="empty"><h2>最初のBURSTを始めよう</h2><p>プレイすると、ここに記録が残るよ。</p></div>'}</div><div class="card"><h2>問題ごとの習熟度</h2>${state.questions.map(q=>{const s=state.questionStats.find(x=>x.id===`${q.id}:${state.settings.direction}`);return `<div class="stat-row"><span>${h(q.prompt)}</span><span>${s?.mastery??'NEW'}<small>${s?.attempts?`${Math.round(s.correct/s.attempts*100)}% · ${(s.totalMs/s.attempts/1000).toFixed(1)}秒`:''}</small></span></div>`;}).join('')}</div></section>`;main.querySelectorAll('[data-session]').forEach(e=>e.onclick=()=>renderResult(state.sessions.find(s=>s.id===e.dataset.session)));}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function renderSettings(){const s=state.settings;main.innerHTML=`<section class="page"><span class="eyebrow">TUNE YOUR BURST</span><h1>自分のリズムで</h1><form id="settings-form" class="card settings-form"><h2>ゲーム</h2><div class="form-grid">${select('difficulty','難易度',[['EASY','EASY · 8秒'],['NORMAL','NORMAL · 6秒'],['HARD','HARD · 4秒'],['EXPERT','EXPERT · 3秒']],s.difficulty)}${select('questionCount','問題数',[[10,'10問'],[20,'20問'],[30,'30問'],[50,'50問'],[100,'100問'],...([10,20,30,50,100].includes(s.questionCount)?[]:[[s.questionCount,`${s.questionCount}問`]])],s.questionCount)}${select('mode','回答方式',[['choice','4択'],['recall','Recall · 答えを見て自己判定']],s.mode)}${select('direction','出題方向',[['forward','問題 → 答え'],['reverse','答え → 問題']],s.direction)}</div><h2>音とリアクション</h2>${select('bgm','BGM',[['OFF','OFF'],['FOCUS','FOCUS · ゆったり集中'],['RUSH','RUSH · 軽快なビート'],['BURST','BURST · 高揚感のあるビート']],s.bgm)}<label>BGM音量 <output id="bgm-value">${Math.round(s.bgmVolume*100)}%</output><input type="range" name="bgmVolume" min="0" max="1" step="0.01" value="${s.bgmVolume}"></label><label>SE音量 <output id="se-value">${Math.round(s.seVolume*100)}%</output><input type="range" name="seVolume" min="0" max="1" step="0.01" value="${s.seVolume}"></label><button type="button" id="preview-audio" class="secondary">音を試す（5秒）</button><label class="check"><input type="checkbox" name="vibration" ${s.vibration?'checked':''}>振動</label><label class="check"><input type="checkbox" name="effects" ${s.effects?'checked':''}>エフェクト</label>${select('effectStrength','エフェクト強度',[['弱','弱'],['標準','標準'],['強','強'],['MAX','MAX']],s.effectStrength)}<p class="hint-text">端末の「動きを減らす」設定では、画面揺れや移動を抑えるよ。画像は現在、同じ基準画像を各リアクションで使用。</p><button class="primary">設定を保存</button></form><div class="card backup-card"><span class="eyebrow">KEEP YOUR MEMORIES</span><h2>データとバックアップ</h2><p>問題・成績・履歴・設定をJSONに保存。端末を変えるときはバックアップしてね。</p><div class="button-grid"><button id="backup-export" class="primary">完全バックアップ</button><button id="ai-export" class="secondary">AI編集用JSON</button><button id="ai-template" class="secondary">AI追加用の指示をコピー</button><button id="persist" class="secondary">保存領域の永続化を申請</button></div><label class="file-label">JSONファイルを選ぶ<input id="import-file" type="file" accept=".json,application/json"></label><label>またはJSONを貼り付け<textarea id="import-text" rows="4" placeholder="AIが作ったJSONもここへ"></textarea></label><button id="import-paste" class="secondary">内容を確認してインポート</button><p class="hint-text">AI編集用は問題とジャンルだけ。AIへ渡す前に、人物名・社内情報など内容を確認してね。自動送信はしないよ。</p></div><div class="card"><h2>ホーム画面・オフライン</h2><button id="install-guide" class="secondary">ホーム画面への追加方法</button><p id="offline-status">オフライン準備を確認中…</p><p class="hint-text">更新があると次回起動で反映。プレイ中は自動更新しないよ。</p></div><div class="card about"><h2>RECALL BURST ${VERSION}</h2><p>アプリ内の人物キャラクターはAI生成による架空のキャラクターです。実在の人物とは関係ありません。</p><p>初期のチーム・担当者はすべて架空。追加した問題はこの端末のIndexedDBだけに保存されます。</p><p>外部AI API・分析SDK・自動同期は使用しません。</p></div></section>`;
 const form=main.querySelector('#settings-form');const readForm=()=>{const f=new FormData(form);return validateSettings({...s,difficulty:f.get('difficulty'),questionCount:Number(f.get('questionCount')),bgm:f.get('bgm'),bgmVolume:Number(f.get('bgmVolume')),seVolume:Number(f.get('seVolume')),vibration:f.has('vibration'),effects:f.has('effects'),effectStrength:f.get('effectStrength'),mode:f.get('mode'),direction:f.get('direction')});};form.onsubmit=async e=>{e.preventDefault();audio.stop();await commit(next=>{next.settings=readForm();});toast('設定を保存したよ');};for(const [key,out] of [['bgmVolume','bgm-value'],['seVolume','se-value']])form.elements[key].oninput=e=>{main.querySelector('#'+out).textContent=`${Math.round(e.target.value*100)}%`;};main.querySelector('#preview-audio').onclick=async()=>{clearTimeout(renderSettings.previewTimer);const settings=readForm();await audio.unlock(settings);audio.start(settings);audio.se('PERFECT');renderSettings.previewTimer=setTimeout(()=>audio.stop(),5000);};main.querySelector('#backup-export').onclick=()=>downloadJSON(exportBackup(state),`recall-burst-backup-${now().slice(0,10)}.json`);main.querySelector('#ai-export').onclick=()=>downloadJSON(exportAI(state),'recall-burst-ai.json');main.querySelector('#ai-template').onclick=async()=>{const text=`RECALL BURSTへ追加する暗記問題を作ってください。次のJSON形式を守り、JSONだけを出力してください。formatとschemaVersionは変更せず、既存項目を編集する場合はIDを維持してください。新規IDは重複しない文字列。各問題に、正解以外の異なる誤答候補を3つ以上入れてください。実在人物や社内情報は、私が提供した内容だけを使い、勝手に作らないでください。\n${JSON.stringify(exampleAI(),null,2)}\n追加したい内容：`;try{await navigator.clipboard.writeText(text);toast('AIへの指示をコピーしたよ');}catch{showDialog(`<h2>AIへの指示</h2><textarea rows="12" readonly>${h(text)}</textarea><button data-close class="secondary">閉じる</button>`);bindDialogClose();}};main.querySelector('#persist').onclick=async()=>toast(await requestPersistence()?'永続保存が許可されたよ':'端末が判断するため、まだ許可されていないよ。バックアップも保存してね');main.querySelector('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){toast('JSONは20MB以内にしてね');return;}try{await previewImport(await file.text());}catch(e){toast(e.message);}};main.querySelector('#import-paste').onclick=()=>previewImport(main.querySelector('#import-text').value);main.querySelector('#install-guide').onclick=installGuide;offlineStatus();}
async function previewImport(text){try{if(text.length>20*1024*1024)throw new Error('JSONは20MB以内にしてね');const data=validateImport(JSON.parse(text));const known=new Set(state.questions.map(q=>q.id));const updates=data.questions.filter(q=>known.has(q.id)).length;showDialog(`<span class="eyebrow">IMPORT PREVIEW</span><h2>インポートを確認</h2><p>${data.kind==='backup'?'完全バックアップ':'AI編集用JSON'}を読み込んだよ。</p><div class="import-counts">ジャンル ${data.decks.length}件 · 問題 ${data.questions.length}件<br>新規 ${data.questions.length-updates}問 · 既存更新 ${updates}問</div>${data.kind==='backup'?'<p>成績・履歴・設定も含まれます。</p>':''}<p>通常は既存データに追加・更新。JSONにない問題も残すよ。</p>${data.kind==='backup'?'<label class="check danger"><input id="replace-data" type="checkbox">バックアップの内容だけに置き換える</label>':''}<p class="hint-text">実行前に、現在の完全バックアップも自動でダウンロードします。</p><div class="dialog-actions"><button data-close class="secondary">キャンセル</button><button id="confirm-import" class="primary">インポートする</button></div>`);bindDialogClose();document.querySelector('#confirm-import').onclick=async e=>{const replace=!!document.querySelector('#replace-data')?.checked;if(replace&&!confirm('現在の全データを、このバックアップで置き換えます。続けますか？'))return;e.target.disabled=true;try{await commit(next=>{downloadJSON(exportBackup(next),`recall-burst-before-import-${Date.now()}.json`);const imported=applyImport(next,data,replace);Object.assign(next,imported);},false);closeDialog();render();toast('インポートできたよ');}catch(error){e.target.disabled=false;toast(error.message);}};}catch(e){toast(e instanceof SyntaxError?'JSONの書式が正しくないよ。コード枠の記号は除いて貼ってね':e.message);}}
function installGuide(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>{installPrompt=null;document.querySelector('#install').hidden=true;});return;}showDialog('<h2>ホーム画面へ追加</h2><p>Android Chromeの右上「︙」→「ホーム画面に追加」または「アプリをインストール」を選んでね。</p><p>インストール項目が出ない時は、このページをChromeで直接開き、初回読み込みの完了を待ってね。</p><button data-close class="primary">わかった</button>');bindDialogClose();}
async function offlineStatus(){const element=main.querySelector('#offline-status');if(!element)return;try{const keys=await caches.keys();element.textContent=keys.some(k=>k.startsWith('yuu-recall-burst-v'))?'✓ オフラインで使う準備ができています':'初回読み込み後、オフラインの準備ができます';}catch{element.textContent='この環境ではオフライン準備を確認できません';}}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#install').hidden=false;});document.querySelector('#install').onclick=installGuide;
addEventListener('appinstalled',()=>{installPrompt=null;document.querySelector('#install').hidden=true;toast('ホーム画面に追加できたよ');});
addEventListener('hashchange',()=>{if(game){game.pause();history.replaceState(null,'',location.pathname+location.search+'#home');return;}audio.stop();effects.clear();render();window.scrollTo(0,0);});
addEventListener('unhandledrejection',e=>{console.error(e.reason);toast('操作を完了できませんでした。'+(e.reason?.message??''));});
function connection(){document.querySelector('#connection').textContent=navigator.onLine?'LOCAL':'OFFLINE';}addEventListener('online',connection);addEventListener('offline',connection);connection();
async function boot(){try{const response=await fetch('./data/seed.json');if(!response.ok)throw new Error('初期データを読み込めませんでした。');const seed=await response.json();seed.characters=CHARACTERS;seed.questions=seed.questions.map(q=>({choices:[],note:'',enabled:true,tags:[],difficulty:'',category:'',createdAt:now(),updatedAt:now(),...q}));state=await lock(()=>initialize(seed));selectedDeck=state.appMeta.find(x=>x.id==='lastDeck')?.deckId;effects.configure(state.settings);render();if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});if(registration.waiting)toast('更新の準備ができたよ。全てのタブを閉じて開き直すと反映されるよ');navigator.serviceWorker.ready.then(()=>offlineStatus());}}catch(e){main.innerHTML=`<section class="page"><h1>起動できませんでした</h1><p>${h(e.message)}</p><p>プライベートモードや保存領域の制限を確認してね。既存データを初期化する処理はしていません。</p><button id="reload" class="primary">再読み込み</button></section>`;main.querySelector('#reload').onclick=()=>location.reload();}}
boot();
