// Offline procedural music: no third-party audio or network requests.
const TRACKS={FOCUS:{bpm:94,notes:[48,55,60,55,50,57,62,57],wave:'sine'},RUSH:{bpm:126,notes:[45,52,57,64,48,55,60,67],wave:'triangle'},BURST:{bpm:142,notes:[48,60,55,67,46,58,53,65],wave:'triangle'}};
const TONES={GOOD:[660,880],GREAT:[660,880,1100],PERFECT:[784,988,1175,1568],MISS:[240,196],COMBO:[523,659,784,1047],FEVER:[523,659,784,1047,1318,1568],CLEAR:[523,659,784,1047,784,1047,1568]};
export class AudioEngine{
 constructor(){this.ctx=null;this.timer=null;this.fever=false;this.musicNodes=new Set();this.step=0;this.ducking=1;}
 async unlock(settings){this.settings=settings;if(!this.ctx){const C=window.AudioContext??window.webkitAudioContext;if(!C)return;this.ctx=new C();}await this.ctx.resume();}
 tone(freq,time,duration,volume,wave='sine',music=false){if(!this.ctx||this.ctx.state!=='running')return;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=wave;osc.frequency.value=freq;gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(Math.max(0.00001,volume),time+0.015);gain.gain.exponentialRampToValueAtTime(0.00001,time+duration);osc.connect(gain);gain.connect(this.ctx.destination);if(music)this.musicNodes.add(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();this.musicNodes.delete(osc);};osc.start(time);osc.stop(time+duration+0.02);}
 start(settings){this.stop();this.settings=settings;this.step=0;this.fever=false;if(settings.bgm==='OFF'||!this.ctx)return;const tick=()=>{if(this.ctx.state!=='running')return;const track=TRACKS[settings.bgm]??TRACKS.BURST;const t=this.ctx.currentTime+0.025;const n=track.notes[this.step%track.notes.length];const hz=440*2**((n-69)/12);const v=settings.bgmVolume*0.18*this.ducking;this.tone(hz,t,0.23,v,track.wave,true);if(this.step%2===0)this.tone(hz/2,t,0.28,v*0.7,'sine',true);if(this.fever){this.tone(hz*2,t,0.12,v*0.8,'sine',true);this.tone(hz*4,t+0.11,0.07,v*0.45,'triangle',true);}if(this.step%4===0)this.tone(70,t,0.12,v*1.2,'sine',true);this.step++;};tick();this.timer=setInterval(tick,60000/(TRACKS[settings.bgm]?.bpm??142)/2);}
 se(type){if(!this.ctx)return;const notes=TONES[type]??TONES.GOOD;notes.forEach((f,i)=>this.tone(f,this.ctx.currentTime+i*0.065,0.16,this.settings.seVolume*0.13,type==='MISS'?'triangle':'sine'));}
 stop(){clearInterval(this.timer);this.timer=null;for(const node of this.musicNodes){try{node.stop();}catch{}}this.musicNodes.clear();}
}
