import {DEFAULT_SETTINGS,LIMITS,SCHEMA_VERSION} from './config.js';
import {now,uid} from './utils.js';
const fail=msg=>{throw new Error(msg);};
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const str=(x,label,max=10000)=>{if(typeof x!=='string'||!x.trim()||x.length>max)fail(`${label}の文字列が不正です。`);return x;};
const num=(x,label,max=1e12)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<0||x>max)fail(`${label}の数値が不正です。`);return x;};
function rows(x,label){if(!Array.isArray(x)||x.length>100000)fail(`${label}の一覧が不正です。`);const ids=new Set();for(const item of x){if(!object(item))fail(`${label}に不正な項目があります。`);str(item.id,'ID',200);if(ids.has(item.id))fail(`${label}内でIDが重複しています。`);ids.add(item.id);}return x;}
function date(x,label){if(typeof x!=='string'||!Number.isFinite(Date.parse(x)))fail(`${label}の日付が不正です。`);return x;}
export function validateSettings(s){if(!object(s))fail('設定の形式が不正です。');const out={...DEFAULT_SETTINGS,...s};if(!(out.difficulty in LIMITS)||!Number.isInteger(out.questionCount)||out.questionCount<1||out.questionCount>100||!['FOCUS','RUSH','BURST','OFF'].includes(out.bgm)||!['choice','recall'].includes(out.mode)||!['forward','reverse'].includes(out.direction)||!['弱','標準','強','MAX'].includes(out.effectStrength)||typeof out.characterId!=='string')fail('設定値が対応範囲外です。');for(const key of ['bgmVolume','seVolume'])num(out[key],key,1);for(const key of ['vibration','effects'])if(typeof out[key]!=='boolean')fail('設定のON/OFFが不正です。');return Object.fromEntries(Object.keys(DEFAULT_SETTINGS).map(k=>[k,out[k]]));}
function normalizeContent(data,ai=false){const t=now();const decks=rows(data.decks,'ジャンル').map(d=>({id:str(d.id,'ジャンルID',200),name:str(d.name,'ジャンル名',120),description:typeof d.description==='string'?d.description.slice(0,1000):'',createdAt:d.createdAt?date(d.createdAt,'作成日時'):t,updatedAt:d.updatedAt?date(d.updatedAt,'更新日時'):t}));const deckIds=new Set(decks.map(d=>d.id));
 const questions=rows(data.questions,'問題').map(q=>{if(!deckIds.has(q.deckId))fail('問題が参照するジャンルがありません。');if(q.choices!==undefined&&(!Array.isArray(q.choices)||q.choices.length>50||q.choices.some(c=>typeof c!=='string'||c.length>1000)))fail('選択肢が不正です。');if(q.tags!==undefined&&(!Array.isArray(q.tags)||q.tags.length>30||q.tags.some(t=>typeof t!=='string'||t.length>100)))fail('タグが不正です。');if(q.enabled!==undefined&&typeof q.enabled!=='boolean')fail('問題の有効設定が不正です。');return{id:q.id,deckId:q.deckId,prompt:str(q.prompt,'問題文',3000),answer:str(q.answer,'答え',1000),choices:[...new Set(q.choices??[])].filter(Boolean),note:typeof q.note==='string'?q.note.slice(0,10000):'',enabled:q.enabled??true,tags:q.tags??[],difficulty:typeof q.difficulty==='string'?q.difficulty:'',category:typeof q.category==='string'?q.category:'',createdAt:q.createdAt?date(q.createdAt,'作成日時'):t,updatedAt:q.updatedAt?date(q.updatedAt,'更新日時'):t};});return{decks,questions};}
export function exportBackup(state){return{format:'recall-burst-backup',app:'RECALL BURST',schemaVersion:SCHEMA_VERSION,exportedAt:now(),...structuredClone(state)};}
export function exportAI(state){return{format:'recall-burst-ai',schemaVersion:SCHEMA_VERSION,exportedAt:now(),instructions:'decks / questions を編集してください。既存IDは維持、新規項目は一意ID。人物名等をAIへ渡す前に内容を確認。choices は正解以外の候補を3つ以上。',decks:structuredClone(state.decks),questions:structuredClone(state.questions)};}
export function validateImport(data){if(!object(data)||data.schemaVersion!==SCHEMA_VERSION||!['recall-burst-ai','recall-burst-backup'].includes(data.format))fail('RECALL BURST v1用JSONではありません。');const content=normalizeContent(data,data.format==='recall-burst-ai');if(data.format==='recall-burst-ai')return{kind:'ai',...content};
 const questionStats=rows(data.questionStats,'問題成績').map(s=>{str(s.questionId,'成績の問題ID',200);if(!['forward','reverse'].includes(s.direction)||s.id!==`${s.questionId}:${s.direction}`||!['NEW','LEARNING','FAMILIAR','MASTERED'].includes(s.mastery))fail('問題成績の形式が不正です。');for(const k of ['attempts','correct','streak','totalMs'])num(s[k],k);if(!Number.isInteger(s.attempts)||!Number.isInteger(s.correct)||!Number.isInteger(s.streak)||s.correct>s.attempts||s.streak>s.correct)fail('成績件数が不正です。');for(const k of ['lastSeen','lastMiss'])if(s[k]!==null)date(s[k],k);return structuredClone(s);});
 const sessions=rows(data.sessions,'履歴').map(s=>{date(s.startedAt,'開始日時');date(s.finishedAt,'終了日時');for(const k of ['score','maxCombo','durationMs'])num(s[k],k);if(!Array.isArray(s.records)||s.records.length>20000)fail('履歴の回答が不正です。');for(const r of s.records){if(!object(r)||!['GOOD','GREAT','PERFECT','MISS'].includes(r.grade)||typeof r.questionId!=='string')fail('履歴の判定が不正です。');num(r.ms,'回答時間');}return structuredClone(s);});
 const characters=rows(data.characters,'キャラクター');const appMeta=rows(data.appMeta,'アプリ情報');return{kind:'backup',...content,questionStats,sessions,characters,appMeta,settings:validateSettings(data.settings)};
}
function mergeRows(oldRows,newRows){const m=new Map(oldRows.map(r=>[r.id,r]));for(const row of newRows)m.set(row.id,structuredClone(row));return [...m.values()];}
export function applyImport(state,validated,replace=false){const next=structuredClone(state);next.decks=replace?validated.decks:mergeRows(next.decks,validated.decks);next.questions=replace?validated.questions:mergeRows(next.questions,validated.questions);
 if(validated.kind==='backup'){for(const name of ['questionStats','sessions','characters','appMeta'])next[name]=replace?validated[name]:mergeRows(next[name],validated[name]);next.settings=validated.settings;}
 if(!next.appMeta.some(x=>x.id==='initialized'))next.appMeta.push({id:'initialized',at:now()});return next;
}
export function exampleAI(){const d=uid();return {format:'recall-burst-ai',schemaVersion:1,decks:[{id:d,name:'新しいジャンル'}],questions:[{id:uid(),deckId:d,prompt:'覚えたい問題',answer:'正解',choices:['誤答A','誤答B','誤答C'],note:'覚えるヒント',enabled:true}]};}
