export const CHARACTERS = [{id:'koharu',name:'小春',folder:'assets/avatars/koharu/',neutral:'neutral.webp',smile:'smile.webp',happy:'happy.webp',delight:'delight.webp',fever:'fever.webp',cheer:'cheer.webp',miss:'miss.webp',clear:'clear.webp'}];
export const character = id => CHARACTERS.find(c=>c.id===id)??CHARACTERS[0];
export function avatarURL(id,state='neutral'){const c=character(id);return new URL('../'+c.folder+(c[state]??c.neutral),import.meta.url).href;}
export async function preloadCharacter(id){const c=character(id);await Promise.all(['neutral','smile','happy','delight','fever','cheer','miss','clear'].map(state=>new Promise(resolve=>{const image=new Image();image.onload=async()=>{try{await image.decode?.();}catch{}resolve();};image.onerror=resolve;image.src=avatarURL(c.id,state);})));}
export function joyLevel(score){return score>=1200?3:score>=500?2:score>0?1:0;}
export function idleExpression(score,combo,index){if(index>0&&(index+1)%6===0)return 'cheer';if(combo>=10)return 'fever';return ['neutral','smile','happy','delight'][joyLevel(score)];}
export function rewardExpression(type,score,combo){if(type==='MISS')return 'miss';if(type==='CLEAR')return 'clear';if(type==='FEVER'||combo>=10)return 'fever';if(combo>0&&combo%5===0)return 'cheer';const gradeLevel={GOOD:1,GREAT:2,PERFECT:3}[type]??0;return ['neutral','smile','happy','delight'][Math.max(gradeLevel,joyLevel(score))];}
export function setCharacter(id,state,combo=0,reaction='neutral',score=0){const stage=document.querySelector('.game-avatar');if(!stage)return;const img=stage.querySelector('img');img.src=avatarURL(id,state);img.alt=`${character(id).name}：${{neutral:'思い出すのを待っている',smile:'うれしそうな笑顔',happy:'明るい笑顔',delight:'大喜び',cheer:'応援のポーズ',fever:'FEVERで大喜び',miss:'次も応援している',clear:'クリアを喜んでいる'}[state]??'笑顔'}`;stage.dataset.expression=state;stage.dataset.joy=joyLevel(score);const label=stage.querySelector('#joy-label');if(label)label.textContent=['',' · うれしい！',' · わくわく！',' · 大喜び！'][joyLevel(score)];stage.dataset.reaction=reaction;stage.style.setProperty('--closeness',String(combo>=20?1.18:combo>=10?1.12:combo>=5?1.08:combo>=3?1.04:1));}
export function reactCharacter(id,type,combo,score=0){setCharacter(id,rewardExpression(type,score,combo),combo,type,score);}
