const PALETTES={GOOD:['#62efd9','#ffffff'],GREAT:['#75ebff','#72ffda','#fff'],PERFECT:['#ffdd80','#ff89bd','#7efcf0','#ffffff'],FEVER:['#ff78a7','#ffe57e','#85fff0'],CLEAR:['#ff91b6','#ffe07a','#87fceb'],MISS:['#d0c4ff']};
export class Effects{
 constructor(){this.canvas=document.querySelector('#fx');this.ctx=this.canvas.getContext('2d');this.particles=[];this.frame=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.resize=()=>{this.dpr=Math.min(devicePixelRatio||1,2);this.width=innerWidth;this.height=innerHeight;this.canvas.width=this.width*this.dpr;this.canvas.height=this.height*this.dpr;this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);};addEventListener('resize',this.resize);this.resize();}
 configure(s){this.settings=s;}
 burst(type,combo=0,word=type){const s=this.settings;if(s.vibration&&!this.reduced.matches&&navigator.vibrate){navigator.vibrate({GOOD:20,GREAT:[20,30,20],PERFECT:[35,35,55],FEVER:[40,35,60,35,80],CLEAR:[35,35,55],MISS:10}[type]??20);}
 if(!s.effects)return;
 const reduced=this.reduced.matches;const multiplier={'弱':0.45,'標準':0.8,'強':1.3,'MAX':2}[s.effectStrength]??1.3;const weight={GOOD:16,GREAT:30,PERFECT:58,FEVER:90,CLEAR:100,MISS:8}[type]??30;const count=Math.min(reduced?16:200,Math.round(weight*multiplier));
 const palette=PALETTES[type]??PALETTES.GREAT;const originY=this.height*(type==='CLEAR'?0.3:0.44);
 for(let i=0;i<count&&this.particles.length<240;i++){const angle=Math.random()*Math.PI*2,speed=(2+Math.random()*7)*(reduced?0.25:multiplier);this.particles.push({x:this.width/2,y:originY,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-2,color:palette[i%palette.length],life:1,decay:0.011+Math.random()*0.02,size:2+Math.random()*4,star:i%4===0});}
 if(!this.frame)this.frame=requestAnimationFrame(t=>this.draw(t));const label=document.querySelector('#burst-word');label.textContent=word;label.dataset.type=type;label.classList.remove('show');void label.offsetWidth;label.classList.add('show');clearTimeout(this.labelTimer);this.labelTimer=setTimeout(()=>label.classList.remove('show'),1000);
 if(!reduced&&type!=='MISS'&&s.effectStrength!=='弱'){const flash=document.querySelector('#flash');flash.classList.remove('pulse');void flash.offsetWidth;flash.classList.add('pulse');document.querySelector('.shell').animate([{transform:'translateX(0)'},{transform:`translateX(${type==='PERFECT'?4:2}px)`},{transform:'translateX(-3px)'},{transform:'translateX(0)'}],{duration:220});}
 const avatar=document.querySelector('.game-avatar');if(avatar&&!reduced&&type!=='MISS')avatar.animate([{filter:'brightness(1)'},{filter:'brightness(1.18)'},{filter:'brightness(1)'}],{duration:650});
 }
 draw(time){const dt=Math.min(2.5,(time-(this.lastTime??time))/16.67);this.lastTime=time;const c=this.ctx;c.clearRect(0,0,this.width,this.height);for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=0.06*dt;p.life-=p.decay*dt;c.globalAlpha=Math.max(0,p.life);c.fillStyle=p.color;if(p.star){c.save();c.translate(p.x,p.y);c.rotate(p.life*4);c.fillRect(-p.size*2,-1,p.size*4,2);c.fillRect(-1,-p.size*2,2,p.size*4);c.restore();}else{c.beginPath();c.arc(p.x,p.y,p.size,0,Math.PI*2);c.fill();}}c.globalAlpha=1;this.particles=this.particles.filter(p=>p.life>0);if(this.particles.length)this.frame=requestAnimationFrame(t=>this.draw(t));else{this.frame=0;this.lastTime=null;c.clearRect(0,0,this.width,this.height);}}
 clear(){cancelAnimationFrame(this.frame);this.frame=0;this.lastTime=null;this.particles=[];this.ctx.clearRect(0,0,this.width,this.height);clearTimeout(this.labelTimer);document.querySelector('#burst-word').classList.remove('show');}
}
