import {LIMITS,POINTS,MILESTONES} from './config.js';
import {buildQueue,makeChoices,scheduleRetry} from './learning.js';
import {avatarURL,reactCharacter} from './characters.js';
import {escapeHTML as h,uid,now} from './utils.js';
import {summarize} from './stats.js';
export function gradeAnswer(correct,ms,limit){return !correct||ms>=limit?'MISS':ms<=limit*0.35?'PERFECT':ms<=limit*0.7?'GREAT':'GOOD';}
export class Game{
 constructor({main,questions,stats,settings,deck,onlyWeak,audio,effects,onAnswer,onFinish}){Object.assign(this,{main,pool:questions,settings,deck,audio,effects,onAnswer,onFinish});this.queue=buildQueue(questions,stats,settings.questionCount,settings.direction,onlyWeak);this.index=0;this.score=0;this.combo=0;this.maxCombo=0;this.records=[];this.retried=new Set();this.limit=LIMITS[settings.difficulty];this.alive=true;this.paused=false;this.locked=false;this.startedAt=now();this.startedPerf=performance.now();this.pauseTotal=0;this.visibility=()=>{if(document.hidden)this.pause();};document.addEventListener('visibilitychange',this.visibility);}
 start(){this.main.innerHTML=`<section class="game" aria-label="暗記ゲーム"><div class="game-top"><div><small>SCORE</small><strong id="score">0</strong></div><div class="combo-box"><small>COMBO</small><strong id="combo">0</strong></div><div><small>PROGRESS</small><strong id="progress"></strong></div></div><div class="game-avatar"><div class="halo"></div><img src="${avatarURL(this.settings.characterId)}" alt="小春"><div class="avatar-badge">KOHARU <i>●</i></div><div class="encourage" id="encourage">いけるよ！</div><div id="fever-label" class="fever-label" hidden>RECALL FEVER</div></div><div class="question-area"><div class="question-meta"><span>${h(this.deck.name)}</span><span>${this.settings.direction==='reverse'?'逆方向':'通常'} · ${this.settings.mode==='recall'?'RECALL':'4択'}</span></div><div class="time-track"><div id="time-fill"></div></div><div id="time-text" class="sr-only"></div><h1 id="prompt"></h1><div id="answers" class="answers"></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div></div><div class="game-controls"><button id="pause" class="quiet">一時停止</button><button id="quit" class="quiet">終了する</button></div><div id="pause-overlay" class="pause-overlay" hidden><div class="card"><span class="eyebrow">TAKE A BREATH</span><h2>ひと休みしよう</h2><p>残り時間は止まっているよ。</p><button id="resume" class="primary">続きをプレイ</button><button id="pause-quit" class="secondary">途中の結果を保存して終了</button></div></div></section>`;
 this.main.querySelector('#pause').onclick=()=>this.pause();this.main.querySelector('#resume').onclick=()=>this.resume();this.main.querySelector('#quit').onclick=()=>this.requestQuit();this.main.querySelector('#pause-quit').onclick=()=>this.requestQuit();this.audio.start(this.settings);this.effects.configure(this.settings);this.next();}
 requestQuit(){this.pause();if(confirm('途中の結果を保存して終了しますか？'))this.finish(true);}
 next(){if(!this.alive)return;if(this.index>=this.queue.length){this.finish(false);return;}this.q=this.queue[this.index];this.locked=false;this.revealed=false;this.elapsed=0;this.questionStart=performance.now();this.questionPause=0;this.main.querySelector('#progress').textContent=`${this.index+1} / ${this.queue.length}`;this.main.querySelector('#prompt').textContent=this.settings.direction==='reverse'?this.q.answer:this.q.prompt;this.main.querySelector('#feedback').textContent='';this.main.querySelector('#feedback').dataset.grade='';this.main.querySelector('#encourage').textContent=this.combo>=10?'この調子！ FEVER中！':this.combo>=3?'いい流れだよ！':'思い出してみよう！';this.main.querySelector('.game-avatar').dataset.reaction='neutral';this.main.querySelector('.game-avatar img').src=avatarURL(this.settings.characterId,this.combo>=10?'fever':'neutral');
 const answers=this.main.querySelector('#answers');if(this.settings.mode==='choice'){const choices=makeChoices(this.q,this.pool,this.settings.direction);if(!choices){this.pause();answers.innerHTML='<p>選択肢が不足しています。問題を追加するかRecallモードにしてください。</p>';return;}answers.innerHTML=choices.map((c,i)=>`<button class="answer" data-index="${i}"><span class="choice-letter">${'ABCD'[i]}</span><span>${h(c)}</span></button>`).join('');answers.querySelectorAll('button').forEach(b=>b.onclick=()=>this.answer(choices[Number(b.dataset.index)]));}else{answers.innerHTML='<button id="reveal" class="primary recall-reveal">答えを見る</button><p class="hint-text">頭の中か声に出して答えてからタップ</p>';answers.querySelector('#reveal').onclick=()=>this.reveal();}
 this.frame=requestAnimationFrame(()=>this.tick());if(this.paused){this.questionPauseStart=performance.now();this.main.querySelector('#pause-overlay').hidden=false;}}
 ms(){return this.elapsed??Math.max(0,performance.now()-this.questionStart-this.questionPause);}
 tick(){if(!this.alive||this.locked||this.paused||this.revealed)return;this.elapsed=Math.max(0,performance.now()-this.questionStart-this.questionPause);const remain=Math.max(0,1-this.elapsed/this.limit);this.main.querySelector('#time-fill').style.transform=`scaleX(${remain})`;this.main.querySelector('#time-fill').classList.toggle('urgent',remain<0.3);this.main.querySelector('#time-text').textContent=`残り${Math.ceil((this.limit-this.elapsed)/1000)}秒`;if(this.elapsed>=this.limit){this.answer(null);return;}this.frame=requestAnimationFrame(()=>this.tick());}
 reveal(){if(this.locked||this.paused)return;this.elapsed=performance.now()-this.questionStart-this.questionPause;if(this.elapsed>=this.limit){this.answer(null);return;}this.revealed=true;cancelAnimationFrame(this.frame);this.main.querySelector('#answers').innerHTML=`<div class="revealed-answer"><small>正解</small><strong>${h(this.settings.direction==='reverse'?this.q.prompt:this.q.answer)}</strong>${this.q.note?`<p>${h(this.q.note)}</p>`:''}</div><div class="recall-actions"><button id="self-correct" class="primary">正解した</button><button id="self-miss" class="secondary">思い出せなかった</button></div>`;this.main.querySelector('#self-correct').onclick=()=>this.answer(true);this.main.querySelector('#self-miss').onclick=()=>this.answer(false);}
 async answer(chosen){if(!this.alive||this.locked||this.paused)return;this.locked=true;cancelAnimationFrame(this.frame);if(!this.revealed)this.elapsed=performance.now()-this.questionStart-this.questionPause;const right=this.settings.direction==='reverse'?this.q.prompt:this.q.answer;const correct=this.settings.mode==='recall'?chosen===true:chosen===right;const grade=gradeAnswer(correct,this.elapsed,this.limit);const success=grade!=='MISS';const oldCombo=this.combo;this.combo=success?this.combo+1:0;this.maxCombo=Math.max(this.maxCombo,this.combo);this.score+=POINTS[grade]+(success?Math.min(50,this.combo*2):0);this.main.querySelector('#score').textContent=this.score;this.main.querySelector('#combo').textContent=this.combo;
 this.main.querySelectorAll('#answers button').forEach(b=>{b.disabled=true;if(this.settings.mode==='choice'){const text=b.lastElementChild.textContent;if(text===right){b.classList.add('correct');b.setAttribute('aria-label',`正解：${right}`);}else if(text===chosen){b.classList.add('wrong');b.setAttribute('aria-label',`不正解：${text}`);}}});
 const message={GOOD:'ちゃんと思い出せたね！',GREAT:'いいね！ かなり覚えてる！',PERFECT:'完璧！！ めっちゃ覚えてる！',MISS:'惜しい！ 次で取り返そう！'}[grade];this.main.querySelector('#encourage').textContent=message;const feedback=this.main.querySelector('#feedback');feedback.dataset.grade=grade;feedback.innerHTML=success?`<strong>${grade}</strong> +${POINTS[grade]+Math.min(50,this.combo*2)}`:`<strong>MISS</strong><div>正解：${h(right)}</div>${this.q.note?`<small>${h(this.q.note)}</small>`:''}`;
 this.main.querySelector('.game').classList.toggle('fever',this.combo>=10);this.main.querySelector('#fever-label').hidden=this.combo<10;this.audio.fever=this.combo>=10;
 if(!success)scheduleRetry(this.queue,this.index,this.q,this.retried);
 const record={questionId:this.q.id,prompt:this.main.querySelector('#prompt').textContent,answer:right,grade,ms:Math.round(this.elapsed),direction:this.settings.direction};this.records.push(record);
 this.reactionTimer=setTimeout(()=>{if(!this.alive)return;reactCharacter(this.settings.characterId,grade,this.combo);if(this.combo===10&&oldCombo===9){this.audio.se('FEVER');this.effects.burst('FEVER',this.combo,'RECALL FEVER');}else if(MILESTONES.includes(this.combo)){this.audio.se('COMBO');this.effects.burst(grade,this.combo,`${this.combo} COMBO!`);}else{this.audio.se(grade);this.effects.burst(grade,this.combo);}},120);
 if(!success){const next=document.createElement('button');next.id='next-question';next.className='secondary';next.textContent='確認した → 次へ';feedback.append(next);this.missReady=performance.now()+1400;next.disabled=true;this.nextTimer=setTimeout(()=>{if(this.alive)next.disabled=false;},1400);next.onclick=async()=>{if(performance.now()<this.missReady)return;next.disabled=true;try{await this.pendingSave;this.advance();}catch{next.disabled=false;}};}
 this.pendingSave=this.onAnswer(record).catch(e=>{this.saveFailed=true;feedback.innerHTML='<strong>保存できませんでした</strong><p>端末の空き容量を確認して、この画面で再試行してください。</p><button id="retry-save" class="secondary">保存を再試行</button>';return new Promise(resolve=>{feedback.querySelector('#retry-save').onclick=async()=>{try{await this.onAnswer(record);this.saveFailed=false;resolve();if(grade==='MISS')this.advance();}catch(err){feedback.querySelector('p').textContent=err.message;}};});});
 if(success){this.nextTimer=setTimeout(async()=>{await this.pendingSave;if(this.alive&&!this.saveFailed)this.advance();},1050);}
 }
 advance(){if(!this.alive||this.advancing)return;this.advancing=true;clearTimeout(this.nextTimer);this.index++;this.advancing=false;this.next();}
 pause(){if(!this.alive||this.paused||this.finishing)return;this.paused=true;this.pauseStart=performance.now();if(!this.locked&&!this.revealed)this.questionPauseStart=this.pauseStart;cancelAnimationFrame(this.frame);this.audio.stop();this.main.querySelector('#pause-overlay').hidden=false;}
 resume(){if(!this.alive||!this.paused)return;const t=performance.now();this.pauseTotal+=t-this.pauseStart;if(this.questionPauseStart){this.questionPause+=t-this.questionPauseStart;this.questionPauseStart=null;}this.paused=false;this.main.querySelector('#pause-overlay').hidden=true;this.audio.start(this.settings);this.audio.fever=this.combo>=10;if(!this.locked&&!this.revealed)this.frame=requestAnimationFrame(()=>this.tick());}
 async finish(aborted){if(!this.alive||this.finishing)return;this.finishing=true;cancelAnimationFrame(this.frame);clearTimeout(this.nextTimer);clearTimeout(this.reactionTimer);this.audio.stop();this.main.querySelector('#pause-overlay').hidden=true;this.main.querySelectorAll('button').forEach(b=>b.disabled=true);await this.pendingSave;if(!this.alive)return;const summary=summarize(this.records);const end=performance.now();const durationMs=Math.round(end-this.startedPerf-this.pauseTotal-(this.paused?end-this.pauseStart:0));const perfectClear=!aborted&&summary.MISS===0&&this.records.length>0;
 if(!aborted){reactCharacter(this.settings.characterId,'CLEAR',this.combo);this.audio.se('CLEAR');this.effects.burst('CLEAR',this.combo,perfectClear?'PERFECT CLEAR!':'CLEAR!');this.main.querySelector('#encourage').textContent=perfectClear?'全部正解！ やったね！！':'おつかれさま！ また一緒に覚えよう！';await new Promise(resolve=>{this.clearTimer=setTimeout(resolve,1500);});}
 if(!this.alive)return;const result={id:uid(),deckId:this.deck.id,deckName:this.deck.name,mode:this.settings.mode,direction:this.settings.direction,difficulty:this.settings.difficulty,startedAt:this.startedAt,finishedAt:now(),score:this.score,maxCombo:this.maxCombo,durationMs,records:this.records,...summary,aborted,perfectClear};this.destroy();await this.onFinish(result);}
 destroy(){this.alive=false;cancelAnimationFrame(this.frame);clearTimeout(this.nextTimer);clearTimeout(this.reactionTimer);this.audio.stop();document.removeEventListener('visibilitychange',this.visibility);}
}
