import test from 'node:test';
import assert from 'node:assert/strict';
import {SpeechReader,detectLanguage,questionLanguage,localVoice,speechChunks} from '../js/speech.js';
import {Game} from '../js/game.js';
import {joyLevel,idleExpression,rewardExpression} from '../js/characters.js';
import {validateImport,exportAI,validateSettings} from '../js/backup.js';
const ja={name:'local ja',lang:'ja-JP',localService:true};
const en={name:'local en',lang:'en-US',localService:true};
class Utterance{constructor(text){this.text=text;}}
function fakeSpeech(voices=[ja,en]){return {voices,spoken:[],listeners:new Set(),cancelCount:0,getVoices(){return this.voices;},speak(u){this.spoken.push(u);},cancel(){this.cancelCount++;},addEventListener(_,fn){this.listeners.add(fn);},removeEventListener(_,fn){this.listeners.delete(fn);},changed(){for(const fn of [...this.listeners])fn();}};}
test('question language follows visible side, script and explicit language metadata',()=>{assert.equal(detectLanguage('青空チーム'),'ja-JP');assert.equal(detectLanguage('remember'),'en-US');assert.equal(detectLanguage('안녕하세요'),'ko-KR');assert.equal(detectLanguage('上海','zh-CN'),'zh-CN');assert.equal(detectLanguage('bonjour','fr-FR'),'fr-FR');const q={prompt:'remember',answer:'覚える',promptLang:'en-US',answerLang:'ja-JP'};assert.equal(questionLanguage(q),'en-US');assert.equal(questionLanguage(q,'reverse'),'ja-JP');});
test('matching local voice is mandatory; remote and wrong-language voices are never used',()=>{assert.equal(localVoice([{...ja,localService:false},en], 'ja-JP'),undefined);assert.equal(localVoice([ja,en], 'en-GB'),en);});
test('switching questions cancels speech and ignores late completion callbacks',()=>{const synth=fakeSpeech(),reader=new SpeechReader({synth,Utterance});let oldDone=0,newDone=0;reader.speak('青空','ja-JP',{onDone:()=>oldDone++});const first=synth.spoken[0];reader.speak('remember','en-US',{onDone:()=>newDone++});const second=synth.spoken[1];assert.equal(first.voice,ja);assert.equal(second.voice,en);first.onend();assert.equal(oldDone,0);assert.equal(newDone,0);second.onstart();second.onend();assert.equal(newDone,1);assert.equal(reader.pending,null);});
test('missing on-device language falls through without sending text remotely',()=>{const synth=fakeSpeech([{...ja,localService:false}]);const reader=new SpeechReader({synth,Utterance});let status;reader.speak('個人情報','ja-JP',{onDone:s=>status=s});assert.equal(status,'unavailable');assert.equal(synth.spoken.length,0);});
test('late voice loading works and listener is removed after cancel or completion',()=>{const synth=fakeSpeech([]),reader=new SpeechReader({synth,Utterance});reader.speak('hello','en-US');assert.equal(synth.spoken.length,0);synth.voices=[en];synth.changed();assert.equal(synth.spoken.length,1);synth.changed();assert.equal(synth.spoken.length,1);assert.equal(synth.listeners.size,0);reader.cancel();assert.equal(reader.pending,null);});
test('long questions are chunked and completion waits for every part',()=>{const text=('長い問題を最後まで読んでください。').repeat(25);const chunks=speechChunks(text);assert(chunks.length>1);assert(chunks.every(s=>s.length<=120));assert.equal(chunks.join(''),text);const synth=fakeSpeech(),reader=new SpeechReader({synth,Utterance});let done=0;reader.speak(text,'ja-JP',{onDone:()=>done++});for(let i=0;i<chunks.length;i++){assert.equal(done,0);synth.spoken[i].onstart();synth.spoken[i].onend();}assert.equal(done,1);assert.equal(synth.spoken.length,chunks.length);});
test('speech watchdog releases unsupported and stalled engines instead of freezing play',t=>{t.mock.timers.enable({apis:['setTimeout']});for(const mode of ['empty','stalled','started']){const synth=fakeSpeech(mode==='empty'?[]:[en]),reader=new SpeechReader({synth,Utterance});let done;reader.speak('hello','en-US',{onDone:s=>done=s});if(mode==='started')synth.spoken[0].onstart();t.mock.timers.tick(21000);assert.equal(done,'unavailable');assert.equal(reader.pending,null);assert.equal(synth.listeners.size,0);}});
test('initial reading holds the timer; replay and canceled speech cannot reset it',t=>{let clock=1000;t.mock.method(performance,'now',()=>clock);globalThis.requestAnimationFrame=()=>1;t.after(()=>{delete globalThis.requestAnimationFrame;});const elements={'#prompt':{textContent:'remember'},'#speak-question':{classList:{add(){},remove(){}},setAttribute(){},dataset:{}},'#speech-status':{textContent:''}};const synth=fakeSpeech();const g=Object.assign(Object.create(Game.prototype),{alive:true,locked:false,paused:false,revealed:false,clockReady:false,questionStart:0,questionPause:0,settings:{speechVolume:1},audio:{ducking:1},promptLang:'en-US',main:{querySelector:s=>elements[s]},speech:new SpeechReader({synth,Utterance})});g.announce(false);clock=5000;assert.equal(g.ms(),0);synth.spoken[0].onstart();synth.spoken[0].onend();assert.equal(g.clockReady,true);clock=5200;assert.equal(g.ms(),200);g.announce(true);clock=5500;synth.spoken[1].onend();assert.equal(g.ms(),500);assert.equal(g.questionStart,5000);g.clockReady=false;g.announce(false);const stale=synth.spoken[2];g.paused=true;g.stopReading(false);stale.onend();assert.equal(g.clockReady,false);assert.equal(g.audio.ducking,1);});
test('joy persists with score, supports occasional cheer and prioritizes FEVER/MISS',()=>{assert.deepEqual([0,1,499,500,1199,1200].map(joyLevel),[0,1,1,2,2,3]);assert.equal(idleExpression(1300,0,0),'delight');assert.equal(idleExpression(700,4,5),'cheer');assert.equal(rewardExpression('GOOD',1300,2),'delight');assert.equal(rewardExpression('GOOD',0,5),'cheer');assert.equal(rewardExpression('PERFECT',1300,10),'fever');assert.equal(rewardExpression('MISS',1300,0),'miss');});
test('language fields survive AI roundtrip, invalid tags reject, old settings remain compatible',()=>{const state={decks:[{id:'d',name:'D'}],questions:[{id:'q',deckId:'d',prompt:'bonjour',answer:'こんにちは',promptLang:'fr-FR',answerLang:'ja-JP'}]};const data=exportAI(state);const parsed=validateImport(data);assert.equal(parsed.questions[0].promptLang,'fr-FR');assert.equal(parsed.questions[0].answerLang,'ja-JP');data.questions[0].promptLang='javascript:alert(1)';assert.throws(()=>validateImport(data));assert.equal(validateSettings({}).readAloud,true);assert.throws(()=>validateSettings({readAloud:'true'}));});
